from . import connector
from . import res_company
from . import res_config_settings
from . import account_move
from . import account_tax
from . import uom_uom
from . import product_template
from . import res_country_state
from . import res_partner
from . import account_fiscal_type